### PR TITLE
Added GitBuildInfo.SourceGenerator.

### PR DESCRIPTION
**Pull request by AraHaan**
I created this generator myself to compete with Nerdbank.GitVersioning.

### CODE REVIEW

**Review by amis92 — CHANGES_REQUESTED** [review]
Thank you for the contribution! Please place your additions in alphabetical order though :)

**Review by amis92 — APPROVED** [review]
Fixed

**Comment by AraHaan** [comment]
Should I also add my ``IDisposableGenerator`` as well?

**Comment by amis92** [comment]
@AraHaan sure, go for it :)

**Pull request merged**
