### PR TITLE
Add phasTrak.AutoRegister

### PR DESCRIPTION
**Pull request by FXZFun**

### CODE REVIEW

**Review by viceroypenguin — CHANGES_REQUESTED** [review]
This package should be rejected, as it (illegally) removes the existing copyright claim from Patrickk in favor of phasTrack.

**Comment by trejjam** [comment]
The original package is MIT. I do not see a real problem (except for some moral aspects)

**Comment by MatthewSteeples** [comment]
The [original licence file](https://github.com/patrickklaeren/AutoRegisterInject/blob/main/LICENSE.txt) indicates that the original copyright must be present "in all copies or substantial portions of the Software".

**Comment by MatthewSteeples** [comment]
Project has been updated now so licencing requirements are fine (cc @viceroypenguin)

**Review by patrickklaeren — COMMENTED** [review]
👎

"Actually useful" seems like a jab at bringing toxicity into the open source community.

I don't think this is very awesome.

Also referenced in phasTrak/ActuallyUseful.AutoRegister#2

**Pull request closed without merging**
