### PR TITLE
Added EnumFastToStringDotNet to list

### PR DESCRIPTION
**Pull request by Spinnernicholas**
Added https://github.com/Spinnernicholas/EnumFastToStringDotNet to list

### CODE REVIEW

**Review by amis92 — CHANGES_REQUESTED** [review]
Please move the entry to be in alphabetical order

**Comment by Spinnernicholas** [comment]
> Please move the entry to be in alphabetical order

Done.

**Review by amis92 — APPROVED** [review]
Thanks!

**Review by amis92 — APPROVED** [review]
Thanks!

**Pull request merged**
